apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mantooth-tasks-dev

resources:
  - ../../base

images:
  - name: ghcr.io/jmansmann/mantooth-tasks
    newTag: dev

patches:
  - path: storage-patch.yaml
