apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mantooth-tasks

resources:
- ../../base
- pvc.yaml

images:
- name: ghcr.io/jmansmann/mantooth-tasks
  newName: ghcr.io/jmansmann/mantooth-tasks
  newTag: sha-6db2a862eedc823f92be32fb82a34a2dbb7cb1c8

patches:
- path: storage-patch.yaml
