apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/jmansmann/mantooth-tasks
    newTag: sha-0000000000000000000000000000000000000000
